# Welcome to Colab!

In [ ]:
import numpy as np

1.
empty_array = np.empty((2, 2))
print("Ans 1:")
print(empty_array)


Ans 1:
[[8.14234537e-316 0.00000000e+000]
 [6.78601892e-310 6.78601878e-310]]


In [ ]:
2.
ones_array = np.ones((4, 2))
print("\n \nAns 2:")
print(ones_array)


 
Ans 2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
3.
filled_array = np.full((6, 7), fill_value=9)
print("\n\nAns 3:")
print(filled_array)



Ans 3:
[[9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]]


In [ ]:
4.
zeros_like_array = np.zeros_like(ones_array)
print("\n\nAns 4:")
print(zeros_like_array)



Ans 4:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
5.
ones_like_array = np.ones_like(filled_array)
print("\n\nAns 5:")
print(ones_like_array)



Ans 5:
[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [ ]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n\nAns 6:")
print(numpy_array)
import numpy as np

print("Ans 1:")
arr1 = np.arange(10, 50)
print(arr1)
print(f"Shape: {arr1.shape}")


print("\n\nAns 2:")
arr2 = np.arange(9)
arr3 = arr2.reshape(3, 3)
print(arr3)

print("\n\nAns 3:")
identity_matrix = np.eye(3)
print(identity_matrix)


print("\n\nAns 4:")
random_array = np.random.random(30)
mean_value = random_array.mean()
print(f"Array: {random_array}")
print(f"Mean: {mean_value}")


print("\n\nAns 5:")
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print(f"Array shape: {random_10x10.shape}")
print(f"Minimum value: {min_value}")
print(f"Maximum value: {max_value}")


print("\n\nAns 6:")
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)


print("\n\nAns 7:")
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(f"Reversed: {reversed_arr}")


print("\n\nAns8:")
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)


print("\n\nAns9:")
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Ans1:")
print("Add (x, y) =",np.add(x, y))

print("\n\nAns2:")
print("Subtract(x, y) =",np.subtract(x, y))

print("\n\nAns 3:")
print("multiply(x, 3) =",np.multiply(x, 3))
print("\nmultiply(y, 2) =",np.multiply(y, 2))


print("\n\nSns4:")
print("Square(x) =",np.square(x))
print("\nsquare(y) =",np.square(y))
print("\nsquare(v) =", np.square(v))

print("\n\nAns5:")
print("\ndot(v, w) =",np.dot(v, w))
print("\ndot(x, v) =",np.dot(x, v))
print("\ndot(x, y) =",np.dot(x, y))


print("\n\nAms6:")
print("\nx and y along row using np.concatenate(axis=0):",np.concatenate((x, y), axis=0))
print("\nUsing np.vstack() for x and y:",np.vstack((x, y)))


print("\n\nAns7:")
xv_concat = np.concatenate((x, v))
print(xv_concat)
# got error because we cannot concatenate arrays which have different dimeensions
#we can fix it by reshaping v  from 1d to 2d



Ans 6:
[1 2 3 4]
Ans 1:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Shape: (40,)


Ans 2:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Ans 3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Ans 4:
Array: [0.76464497 0.11448568 0.14352648 0.74798451 0.68838416 0.84164073
 0.48655339 0.92898909 0.40337076 0.47471184 0.97376495 0.55807243
 0.28207021 0.31487905 0.70840019 0.21650043 0.81739245 0.53291356
 0.64056165 0.00265496 0.1775814  0.73118853 0.97858194 0.48162638
 0.80645301 0.88089711 0.39131145 0.20855041 0.33103754 0.51249324]
Mean: 0.5380407494590127


Ans 5:
Array shape: (10, 10)
Minimum value: 0.01729938635865713
Maximum value: 0.9890944225068394


Ans 6:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Ans 7:
Reversed: [0 4 0 0 2 1]


Ans8:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Ans9:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

In [ ]:
#Prove A·A⁻¹ = I
A_inv = np.linalg.inv(A)
print("A·A⁻¹ =")
print(A @ A_inv)


A·A⁻¹ =
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
#Prove AB ≠ BA
AB = A @ B
BA = B @ A
print("\nAB =", AB)
print("BA =", BA)


AB = [[23 13]
 [51 29]]
BA = [[36 44]
 [13 16]]


In [ ]:
#Prove (AB)ᵀ = BᵀAᵀ
AB_T = (A @ B).T
BT_AT = B.T @ A.T
print("\n(AB)ᵀ =", AB_T)
print("BᵀAᵀ =", BT_AT)


(AB)ᵀ = [[23 51]
 [13 29]]
BᵀAᵀ = [[23 51]
 [13 29]]


In [ ]:
#Solve system: AX = B
coeff = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])
const = np.array([-1, -3, 9])

In [ ]:
#Using inverse method: X = A⁻¹B
solution = np.linalg.inv(coeff) @ const
print("\nSolution:", solution)



Solution: [ 2.  1. -2.]


In [ ]:
#Using np.linalg.solve (more efficient)
solution2 = np.linalg.solve(coeff, const)
print("Solution (linalg.solve):", solution2)

Solution (linalg.solve): [ 2.  1. -2.]
