<a href="https://colab.research.google.com/github/ayush1221-right/AI_2461973_Ayush/blob/main/worksheet_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

print("=" * 60)
print("Problem 4.1: Array Creation with NumPy")
print("=" * 60)

Problem 4.1: Array Creation with NumPy


In [3]:
# Task 1: Initialize an empty array with size 2x2
print("\n1. Empty array with size 2x2:")
empty_array = np.empty((2, 2))
print(empty_array)
print(f"Shape: {empty_array.shape}")


1. Empty array with size 2x2:
[[1.91701580e-315 0.00000000e+000]
 [6.63891356e-310 5.77904633e-317]]
Shape: (2, 2)


In [4]:
# Task 2: Initialize an all ones array with size 4x2
print("\n2. All ones array with size 4x2:")
ones_array = np.ones((4, 2))
print(ones_array)
print(f"Shape: {ones_array.shape}")


2. All ones array with size 4x2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Shape: (4, 2)


In [5]:
# Task 3: Return a new array filled with a specific fill value
print("\n3. Array filled with custom value (e.g., 7) with shape 3x3:")
fill_value = 7
filled_array = np.full((3, 3), fill_value)
print(filled_array)
print(f"Shape: {filled_array.shape}")


3. Array filled with custom value (e.g., 7) with shape 3x3:
[[7 7 7]
 [7 7 7]
 [7 7 7]]
Shape: (3, 3)


In [6]:
# Task 4: Return a new array of zeros with same shape and type as given array
print("\n4. Zeros array with same shape as reference array:")
reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)
print(f"Reference array:\n{reference_array}")
print(f"Zeros like array:\n{zeros_like_array}")
print(f"Shape: {zeros_like_array.shape}")


4. Zeros array with same shape as reference array:
Reference array:
[[1 2 3]
 [4 5 6]]
Zeros like array:
[[0 0 0]
 [0 0 0]]
Shape: (2, 3)


In [7]:
# Task 5: Return a new array of ones with same shape and type as given array
print("\n5. Ones array with same shape as reference array:")
ones_like_array = np.ones_like(reference_array)
print(f"Reference array:\n{reference_array}")
print(f"Ones like array:\n{ones_like_array}")
print(f"Shape: {ones_like_array.shape}")



5. Ones array with same shape as reference array:
Reference array:
[[1 2 3]
 [4 5 6]]
Ones like array:
[[1 1 1]
 [1 1 1]]
Shape: (2, 3)


In [8]:
# Task 6: Convert existing list to numpy array
print("\n6. Convert list to numpy array:")
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print(f"Original list: {new_list}")
print(f"NumPy array: {array_from_list}")
print(f"Type: {type(array_from_list)}")
print(f"Shape: {array_from_list.shape}")

print("\n" + "=" * 60)
print("All tasks completed successfully!")
print("=" * 60)



6. Convert list to numpy array:
Original list: [1, 2, 3, 4]
NumPy array: [1 2 3 4]
Type: <class 'numpy.ndarray'>
Shape: (4,)

All tasks completed successfully!


In [9]:
# Task 1: Create an array with values ranging from 10 to 49
print("1. Array with values ranging from 10 to 49:")
array_range = np.arange(10, 50)
print(array_range)
print(f"Shape: {array_range.shape}")


1. Array with values ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Shape: (40,)


In [10]:
# Task 2: Create a 3x3 matrix with values ranging from 0 to 8
print("\n2. 3x3 matrix with values ranging from 0 to 8:")
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
print(matrix_3x3)
print(f"Shape: {matrix_3x3.shape}")


2. 3x3 matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Shape: (3, 3)


In [11]:
# Task 3: Create a 3x3 identity matrix
print("\n3. 3x3 identity matrix:")
identity_matrix = np.eye(3)
print(identity_matrix)
print(f"Shape: {identity_matrix.shape}")



3. 3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape: (3, 3)


In [12]:
# Task 4: Create a random array of size 30 and find the mean
print("\n4. Random array of size 30 and its mean:")
random_array = np.random.random(30)
mean_value = random_array.mean()
print(f"Random array: {random_array}")
print(f"Mean value: {mean_value:.4f}")


4. Random array of size 30 and its mean:
Random array: [0.94986856 0.27976294 0.42585029 0.49586696 0.90054551 0.65280592
 0.85616932 0.1420167  0.52997639 0.90223555 0.17140827 0.57539332
 0.01485302 0.11553254 0.39672521 0.6326233  0.75149838 0.50228819
 0.08651288 0.58436189 0.49645637 0.82110614 0.81410581 0.88814207
 0.23834526 0.2162369  0.43740897 0.83675688 0.28399489 0.4421483 ]
Mean value: 0.5147


In [13]:
# Task 5: Create a 10x10 array with random values and find min and max
print("\n5. 10x10 array with random values - min and max:")
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print(f"10x10 Random array:\n{random_10x10}")
print(f"Minimum value: {min_value:.4f}")
print(f"Maximum value: {max_value:.4f}")



5. 10x10 array with random values - min and max:
10x10 Random array:
[[0.3155786  0.90655099 0.95528989 0.03025749 0.30234259 0.88907669
  0.70508872 0.03963695 0.11192365 0.41897393]
 [0.36937    0.08201918 0.87635398 0.77942669 0.42412868 0.23869534
  0.31494488 0.1282927  0.27110303 0.98680932]
 [0.59765839 0.77985024 0.59081942 0.55144807 0.78373437 0.85376271
  0.23277038 0.16483588 0.19355245 0.75605726]
 [0.6399893  0.28796965 0.07100271 0.46753297 0.63488022 0.04394916
  0.0758091  0.15192301 0.209969   0.97156742]
 [0.15289962 0.30840552 0.42668481 0.94030396 0.81862425 0.55320705
  0.39218079 0.8617971  0.23126788 0.23532487]
 [0.41211015 0.98085403 0.01242567 0.43295291 0.94019236 0.17771228
  0.6496318  0.02167241 0.86382787 0.94081936]
 [0.99331208 0.80509771 0.14849954 0.47408179 0.36749234 0.33225992
  0.19612332 0.15662319 0.76651576 0.36032763]
 [0.45361471 0.33090559 0.00957424 0.34331353 0.59451666 0.91224938
  0.95354157 0.77844139 0.84145025 0.38328966]
 [0.820584

In [14]:
# Task 6: Create a zero array of size 10 and replace 5th element with 1
print("\n6. Zero array with 5th element replaced by 1:")
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (index 4)
print(zero_array)


6. Zero array with 5th element replaced by 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
# Task 7: Reverse an array
print("\n7. Reverse an array:")
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(f"Original array: {arr}")
print(f"Reversed array: {reversed_arr}")



7. Reverse an array:
Original array: [1 2 0 0 4 0]
Reversed array: [0 4 0 0 2 1]


In [16]:
# Task 8: Create a 2d array with 1 on border and 0 inside
print("\n8. 2D array with 1 on border and 0 inside (5x5 example):")
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)


8. 2D array with 1 on border and 0 inside (5x5 example):
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
# Task 9: Create an 8x8 matrix and fill it with a checkerboard pattern
print("\n9. 8x8 matrix with checkerboard pattern:")
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Odd rows, even columns
checkerboard[::2, 1::2] = 1  # Even rows, odd columns
print(checkerboard)

print("\nAll tasks completed!")



9. 8x8 matrix with checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

All tasks completed!


In [20]:
# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("Given arrays:")
print(f"x = \n{x}")
print(f"y = \n{y}")
print(f"v = {v}")
print(f"w = {w}")


Given arrays:
x = 
[[1 2]
 [3 5]]
y = 
[[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]


In [21]:
# Task 1: Add the two arrays
print("\n1. Add x and y:")
addition = x + y
print(addition)


1. Add x and y:
[[ 6  8]
 [10 13]]


In [22]:
# Task 2: Subtract the two arrays
print("\n2. Subtract y from x:")
subtraction = x - y
print(subtraction)



2. Subtract y from x:
[[-4 -4]
 [-4 -3]]


In [23]:
# Task 3: Multiply the array with any integer
print("\n3. Multiply x by 3:")
multiplication = x * 3
print(multiplication)


3. Multiply x by 3:
[[ 3  6]
 [ 9 15]]


In [24]:
# Task 4: Find the square of each element
print("\n4. Square of each element in x:")
square = x ** 2
print(square)


4. Square of each element in x:
[[ 1  4]
 [ 9 25]]


In [26]:
# Task 5: Find the dot product
print("\n5. Dot products:")
print("   a) Dot product of v and w:")
dot_vw = np.dot(v, w)
print(f"   {dot_vw}")

print("   b) Dot product of x and v:")
dot_xv = np.dot(x, v)
print(f"   {dot_xv}")

print("   c) Dot product of x and y:")
dot_xy = np.dot(x, y)
print(f"\n{dot_xy}")



5. Dot products:
   a) Dot product of v and w:
   219
   b) Dot product of x and v:
   [29 77]
   c) Dot product of x and y:

[[19 22]
 [50 58]]


In [28]:
# Task 6: Concatenate arrays
print("\n6. Concatenation:")
print("   a) Concatenate x and y along rows (vertically):")
concat_row = np.vstack((x, y))
# Alternative: concat_row = np.concatenate((x, y), axis=0)
print(f"{concat_row}")

print("   b) Concatenate v and w along columns (horizontally):")
# Need to reshape v and w to column vectors first
v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)
concat_col = np.hstack((v_col, w_col))
# Alternative: concat_col = np.concatenate((v_col, w_col), axis=1)
print(f"{concat_col}")



6. Concatenation:
   a) Concatenate x and y along rows (vertically):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
   b) Concatenate v and w along columns (horizontally):
[[ 9 11]
 [10 12]]


In [29]:
# Task 7: Try to concatenate x and v
print("\n7. Attempt to concatenate x and v:")
try:
    concat_xv = np.concatenate((x, v))
    print(concat_xv)
except ValueError as e:
    print(f"   Error occurred: {e}")
    print("\n   Explanation:")
    print(f"   - x has shape {x.shape} (2D array: 2 rows, 2 columns)")
    print(f"   - v has shape {v.shape} (1D array: 2 elements)")
    print("   - Arrays must have compatible dimensions for concatenation")
    print("   - x is 2D while v is 1D, causing a shape mismatch")
    print("   - To fix this, v needs to be reshaped to match x's dimensions")
    print("\n   Possible solutions:")
    print("   - Reshape v to (1, 2): np.concatenate((x, v.reshape(1, 2)), axis=0)")
    print("   - Or reshape v to (2, 1): np.concatenate((x, v.reshape(2, 1)), axis=1)")

print("\nAll tasks completed!")


7. Attempt to concatenate x and v:
   Error occurred: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

   Explanation:
   - x has shape (2, 2) (2D array: 2 rows, 2 columns)
   - v has shape (2,) (1D array: 2 elements)
   - Arrays must have compatible dimensions for concatenation
   - x is 2D while v is 1D, causing a shape mismatch
   - To fix this, v needs to be reshaped to match x's dimensions

   Possible solutions:
   - Reshape v to (1, 2): np.concatenate((x, v.reshape(1, 2)), axis=0)
   - Or reshape v to (2, 1): np.concatenate((x, v.reshape(2, 1)), axis=1)

All tasks completed!


In [30]:
import numpy as np

# Define the matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("Given matrices:")
print(f"A = \n{A}")
print(f"\nB = \n{B}")

Given matrices:
A = 
[[3 4]
 [7 8]]

B = 
[[5 3]
 [2 1]]


In [31]:
# Task 1: Prove A.A^(-1) = I
print("\n" + "="*60)
print("1. Prove A·A^(-1) = I")
print("="*60)
A_inv = np.linalg.inv(A)
print(f"A^(-1) = \n{A_inv}")

product_A_Ainv = np.dot(A, A_inv)
print(f"\nA·A^(-1) = \n{product_A_Ainv}")

# Round to remove floating point errors
product_rounded = np.round(product_A_Ainv)
print(f"\nA·A^(-1) (rounded) = \n{product_rounded}")

identity_2x2 = np.eye(2)
print(f"\nIdentity matrix I = \n{identity_2x2}")
print(f"\nVerification: A·A^(-1) = I? {np.allclose(product_A_Ainv, identity_2x2)}")


1. Prove A·A^(-1) = I
A^(-1) = 
[[-2.    1.  ]
 [ 1.75 -0.75]]

A·A^(-1) = 
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

A·A^(-1) (rounded) = 
[[1. 0.]
 [0. 1.]]

Identity matrix I = 
[[1. 0.]
 [0. 1.]]

Verification: A·A^(-1) = I? True


In [32]:
# Task 2: Prove AB ≠ BA
print("\n" + "="*60)
print("2. Prove AB ≠ BA")
print("="*60)
AB = np.dot(A, B)
BA = np.dot(B, A)

print(f"AB = \n{AB}")
print(f"\nBA = \n{BA}")
print(f"\nAre AB and BA equal? {np.array_equal(AB, BA)}")
print("Therefore, AB ≠ BA (Matrix multiplication is not commutative)")



2. Prove AB ≠ BA
AB = 
[[23 13]
 [51 29]]

BA = 
[[36 44]
 [13 16]]

Are AB and BA equal? False
Therefore, AB ≠ BA (Matrix multiplication is not commutative)


In [33]:
# Task 3: Prove (AB)^T = B^T·A^T
print("\n" + "="*60)
print("3. Prove (AB)^T = B^T·A^T")
print("="*60)
AB_transpose = AB.T
print(f"(AB)^T = \n{AB_transpose}")

B_transpose = B.T
A_transpose = A.T
print(f"\nB^T = \n{B_transpose}")
print(f"\nA^T = \n{A_transpose}")

BT_AT = np.dot(B_transpose, A_transpose)
print(f"\nB^T·A^T = \n{BT_AT}")

print(f"\nAre (AB)^T and B^T·A^T equal? {np.array_equal(AB_transpose, BT_AT)}")
print("Therefore, (AB)^T = B^T·A^T ✓")



3. Prove (AB)^T = B^T·A^T
(AB)^T = 
[[23 51]
 [13 29]]

B^T = 
[[5 2]
 [3 1]]

A^T = 
[[3 7]
 [4 8]]

B^T·A^T = 
[[23 51]
 [13 29]]

Are (AB)^T and B^T·A^T equal? True
Therefore, (AB)^T = B^T·A^T ✓


In [35]:
 #Task 4: Solve system of linear equations
print("\n" + "="*60)
print("4. Solve System of Linear Equations using Inverse Method")
print("="*60)
print("System of equations:")
print("2x - 3y + z = -1")
print("x - y + 2z = -3")
print("3x + y - z = 9")

# Coefficient matrix A
coeff_matrix = np.array([[2, -3, 1],
                         [1, -1, 2],
                         [3, 1, -1]])

# Constants matrix B
constants = np.array([-1, -3, 9])

print(f"\nCoefficient matrix A = \n{coeff_matrix}")
print(f"\nConstants matrix B = \n{constants}")

#  Using matrix inverse
print("\n--- Using Matrix Inverse (A^(-1)·B) ---")
coeff_inv = np.linalg.inv(coeff_matrix)
print(f"A^(-1) = \n{coeff_inv}")

solution_method1 = np.dot(coeff_inv, constants)
print(f"\nSolution X = A^(-1)·B = \n{solution_method1}")
print(f"\nTherefore:")
print(f"x = {solution_method1[0]}")
print(f"y = {solution_method1[1]}")
print(f"z = {solution_method1[2]}")


4. Solve System of Linear Equations using Inverse Method
System of equations:
2x - 3y + z = -1
x - y + 2z = -3
3x + y - z = 9

Coefficient matrix A = 
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Constants matrix B = 
[-1 -3  9]

--- Using Matrix Inverse (A^(-1)·B) ---
A^(-1) = 
[[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution X = A^(-1)·B = 
[ 2.  1. -2.]

Therefore:
x = 2.0
y = 1.0
z = -2.0


In [38]:
# Verification
print("\n--- Verification: Check if A·X = B ---")
verification = np.dot(coeff_matrix, solution_method1)
print(f"A·X = \n{verification}")
print(f"B = \n{constants}")
print(f"Is A·X = B? {np.allclose(verification, constants)}")

print("\nAll tasks completed!")


--- Verification: Check if A·X = B ---
A·X = 
[-1. -3.  9.]
B = 
[-1 -3  9]
Is A·X = B? True

All tasks completed!
